### ISSUE TITLE
Publish new release

### ISSUE THREAD

**Issue by Bouke** [plumdog/django-password-protect#3]
There's a bugfix committed to master which hasn't made it to pypi yet. Could you release a new version? Thanks!

**Comment by plumdog** [comment]
I believe I have successfully done this:
https://pypi.python.org/pypi/Django-Password-Protect/0.0.2

**Comment by plumdog** [comment]
I have also just released [`0.0.3`](https://pypi.python.org/pypi/Django-Password-Protect/0.0.3) which I hope hasn't broken any of the previous fixes.
